version: 2
jobs:
  install_deps:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:8.5-browsers
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
  build_release:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:8.5-browsers
    steps:
      - checkout
      - run:
          name: Build release files
          command: npm run build
  
  exec_unit_tests:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:8.5-browsers
    steps:
      - checkout
      - run:
          name: Unit Tests
          command: npm run test:once
workflows:
  version: 2
  build_and_test:
    jobs:
      - install_deps
      - build_release:
          requires:
            - install_deps
          filters:
            branches:
              only:
                - develop
                - master
      - exec_unit_tests:
          requires:
            - install_deps