version: 2
jobs:
  install:
    working_directory: ~/tmp
    docker:
      - image: circleci/mode:8.5-browsers
    steps:
      - checkout
      - run:
        name: Update npm
        command: 'sudo npm install -g npm@latest'
      - restore_cache:
        key: dependency-cache-{{ checksum "package.json" }}
      - run:
        name: Install npm dependencies
        command: npm install
      - save_cache:
        key: dependency-cache-{{ checksum "package.json" }}
        paths:
          - node_modules
  
  build:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:8.5-browsers
    steps:
      - checkout
      - run:
        name: Build release files
        command: npm run build
  
  test:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:8.5-browsers
    steps:
      - checkout
      - run:
        name: Unit Tests
        command: npm run test:once

workflows:
  version: 2
  build_and_test:
    jobs:
      - install
      - build
        requires:
          - install
      - test:
        requires:
           - install